
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import StyledComponentsRegistry from '@/lib/AntdRegistry'
import Navbar from '@/components/Navbar'
import { TodosProvider } from '@/components/store/todos'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Todo App',
  description: 'Generated by create next app $ antd $ typescript',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <StyledComponentsRegistry>
            <TodosProvider>
              {children}
            </TodosProvider>
          </StyledComponentsRegistry>  
      </body>
    </html>
  )
}
